---
title: "Generating Imbalanced Data"
author: "Daniel K Baissa"
date: "2023-01-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(caret)
```



Maybe I can create a vector of variables, coeficients, and mathematical symbols and randomly put them together to create random datasets? Then I can sample from the imbalanced ones for the paper?


```{r}
num <- 1:10
2 + sample(num, 1)
```

```{r}

```


```{r}

set.seed(11)

n  = 800 
p = 5 ## number of predictors  
X = data.frame(matrix(runif(n * p), ncol = p))

z = rnorm(n)*rnorm(X[ ,1]) + rnorm(n)*rnorm(X[ ,2]) + rnorm(n)*rnorm(X[ ,3]) + rnorm(n)*rnorm(X[ ,4]) + rnorm(n)*rnorm(X[ ,5])

pr = 1/(1+exp(-z))         # pass through an inv-logit function  

y = as.factor(rbinom(n,1,pr))

sum(as.numeric(y)-1)/length(y)
```

Now let's try with randomly picking variables

```{r}
set.seed(11)

n  = 800 
p = 5 ## number of predictors  
X = data.frame(matrix(runif(n * p), ncol = p))

pre <- 1:5

z = rnorm(n)*rnorm(X[ ,sample(pre, 1)]) + rnorm(n)*rnorm(X[ ,sample(pre, 1)]) + rnorm(n)*rnorm(X[ ,sample(pre, 1)]) + rnorm(n)*rnorm(X[ ,sample(pre, 1)]) + rnorm(n)*rnorm(X[ ,sample(pre, 1)])

pr = 1/(1+exp(-z))         # pass through an inv-logit function  

y = as.factor(rbinom(n,1,pr))

sum(as.numeric(y)-1)/length(y)
```

Created using GPT-3

```{r}

y = x1 + x2 + x3 + x4 + x5

y = x1 * x2 * x3 * x4 * x5

y = (x1 + x2 + x3 + x4 + x5)^2

y = 1/(x1 + x2 + x3 + x4 + x5)

y = exp(x1 + x2 + x3 + x4 + x5)

y = x1^2 + x2^2 + x3^2 + x4^2 + x5^2

y = sqrt(x1^2 + x2^2 + x3^2 + x4^2 + x5^2)

y = x1^3 + x2^3 + x3^3 + x4^3 + x5^3

y = (x1 * x2 * x3) / (x4 * x5)

y = (x1 / x2) + (x3 / x4) + (x5 / x6)

y = (x1^2 / x2^2) + (x3^2 / x4^2) + (x5^2 / x6^2)

y = 1 / ((x1 / x2) + (x3 / x4) + (x5 / x6))

y = exp((x1 / x2) + (x3 / x4) + (x5 / x6))

y = x1 + (x2 / x3) + (x4 / x5) + (x6 / x7)

y = x1 * (x2 / x3) * (x4 / x5) * (x6 / x7)

y = (x1 + (x2 / x3) + (x4 / x5) + (x6 / x7))^2

y = 1 / (x1 + (x2 / x3) + (x4 / x5) + (x6 / x7))

y = exp(x1 + (x2 / x3) + (x4 / x5) + (x6 / x7))

y = x1^2 + (x2 / x3)^2 + (x4 / x5)^2 + (x6 / x7)^2

y = sqrt(x1^2 + (x2 / x3)^2 + (x4 / x5)^2 + (x6 / x7)^2)

y = x1^3 + (x2 / x3)^3 + (x4 / x5)^3 + (x6 / x7)^3

y = (x1 * (x2 / x3) * (x4 / x5)) / (x6 * x7)

y = (x1 / (x2 / x3)) + (x4 / (x5 / x6)) + (x7 / (x8 / x9))

y = (x1^2 / (x2 / x3)^2) + (x4^2 / (x5 / x6)^2) + (x7^2 / (x8 / x9)^2)

y = 1 / ((x1 / (x2 / x3)) + (x4 / (x5 / x6)) + (x7 / (x8 / x9)))

y = exp((x1 / (x2 / x3)) + (x4 / (x5 / x6)) + (x7 / (x8 / x9)))

y = x1 + (x2 / (x3 / x4)) + (x5 / (x6 / x7)) + (x8 / (x9 / x10))

y = x1 * (x2 / (x3 / x4)) * (x5 / (x6 / x7)) * (x8 / (x9 / x10))

y = (x1 + (x2 / (x3 / x4)) + (x5 / (x6 / x7)) + (x8 / (x9 / x10)))^2

y = 1 / (x1 + (x2 / (x3 / x4)) + (x5 / (x6 / x7)) + (x8 / (x9 / x10)))

y = exp(x1 + (x2 / (x3 / x4)) + (x5 / (x6 / x7)) + (x8 / (x9 / x10)))

y = x1^2 + (x2 / (x3 / x4))^2 + (x5 / (x6 / x7))^2 + (x8 / (x9 / x10))^2

y = sqrt(x1^2 + (x2 / (x3 / x4))^2 + (x5 / (x6 / x7))^2 + (x8 / (x9 / x10))^2)

#create 50 more

y = x1 + x2 + x3 + x4 + x5

y = x1 * x2 * x3 * x4 * x5

y = (x1 + x2 + x3 + x4 + x5)^2

y = 1/(x1 + x2 + x3 + x4 + x5)

y = exp(x1 + x2 + x3 + x4 + x5)

y = x1^2 + x2^2 + x3^2 + x4^2 + x5^2

y = sqrt(x1^2 + x2^2 + x3^2 + x4^2 + x5^2)

y = x1^3 + x2^3 + x3^3 + x4^3 + x5^3

y = (x1 * x2 * x3) / (x4 * x5)

y = (x1 / x2) + (x3 / x4) + (x5 / x6)

y = (x1^2 / x2^2) + (x3^2 / x4^2) + (x5^2 / x6^2)

y = 1 / ((x1 / x2) + (x3 / x4) + (x5 / x6))

y = exp((x1 / x2) + (x3 / x4) + (x5 / x6))

y = x1 + (x2 / x3) + (x4 / x5) + (x6 / x7)

y = x1 * (x2 / x3) * (x4 / x5) * (x6 / x7)

y = (x1 + (x2 / x3) + (x4 / x5) + (x6 / x7))^2

y = 1 / (x1 + (x2 / x3) + (x4 / x5) + (x6 / x7))

y = exp(x1 + (x2 / x3) + (x4 / x5) + (x6 / x7))

y = x1^2 + (x2 / x3)^2 + (x4 / x5)^2 + (x6 / x7)^2

y = sqrt(x1^2 + (x2 / x3)^2 + (x4 / x5)^2 + (x6 / x7)^2)

y = x1^3 + (x2 / x3)^3 + (x4 / x5)^3 + (x6 / x7)^3

y = (x1 * (x2 / x3) * (x4 / x5)) / (x6 * x7)

y = (x1 / (x2 / x3)) + (x4 / (x5 / x6)) + (x7 / (x8 / x9))

y = (x1^2 / (x2 / x3)^2) + (x4^2 / (x5 / x6)^2) + (x7^2 / (x8 / x9)^2)

y = 1 / ((x1 / (x2 / x3)) + (x4 / (x5 / x6)) + (x7 / (x8 / x9)))

y = exp((x1 / (x2 / x3)) + (x4 / (x5 / x6)) + (x7 / (x8 / x9)))

y = x1 + (x2 / (x3 / x4)) + (x5 / (x6 / x7)) + (x8 / (x9 / x10))

y = x1 * (x2 / (x3 / x4)) * (x5 / (x6 / x7)) * (x8 / (x9 / x10))

y = (x1 + (x2 / (x3 / x4)) + (x5 / (x6 / x7)) + (x8 / (x9 / x10)))^2

y = 1 / (x1 + (x2 / (x3 / x4)) + (x5 / (x6 / x7)) + (x8 / (x9 / x10)))

y = exp(x1 + (x2 / (x3 / x4)) + (x5 / (x6 / x7)) + (x8 / (x9 / x10)))

y = x1^2 + (x2 / (x3 / x4))^2 + (x5 / (x6 / x7))^2 + (x8 / (x9 / x10))^2

y = sqrt(x1^2 + (x2 / (x3 / x4))^2 + (x5 / (x6 / x7))^2 + (x8 / (x9 / x10))^2)

y = x1^3 + (x2 / (x3 / x4))^3 + (x5 / (x6 / x7))^3 + (x8 / (x9 / x10))^3

y = (x1 * ((x2 / (x3 / x4)) / (x5 / (x6 / x7)))) / (x8 / (x9 / x10))

y = (x1 / ((x2 / (x3 / x4)) * (x5 / (x6 / x7)))) + (x8 / ((x9 / x10) * (x11 / x12))) + (x13 / ((x14 / x15) * (x16 / x17)))

y = (x1^2 / ((x2 / (x3 / x4))^2 * (x5 / (x6 / x7))^2)) + (x8^2 / ((x9 / x10)^2 * (x11 / x12)^2)) + (x13^2 / ((x14 / x15)^2 * (x16 / x17)^2))

y = 1 / ((x1 / ((x2 / (x3 / x4)) * (x5 / (x6 / x7)))) + (x8 / ((x9 / x10) * (x11 / x12))) + (x13 / ((x14 / x15) * (x16 / x17))))

y = exp((x1 / ((x2 / (x3 / x4)) * (x5 / (x6 / x7)))) + (x8 / ((x9 / x10) * (x11 / x12))) + (x13 / ((x14 / x15) * (x16 / x17))))

y = x1 + ((x2 / (x3 / x4)) * (x5 / (x6 / x7))) + (x8 / ((x9 / x10) * (x11 / x12))) + (x13 / ((x14 / x15) * (x16 / x17)))

y = x1 * ((x2 / (x3 / x4)) / (x5 / (x6 / x7))) * (x8 / ((x9 / x10) * (x11 / x12))) * (x13 / ((x14 / x15) * (x16 / x17)))

y = ((x1 + ((x2 / (x3 / x4)) * (x5 / (x6 / x7)))) / (x8 / ((x9 / x10) * (x11 / x12)))) + (x13 / ((x14 / x15) * (x16 / x17)))

y = ((x1^2 + ((x2 / (x3 / x4))^2 * (x5 / (x6 / x7))^2)) / (x8^2 / ((x9 / x10)^2 * (x11 / x12)^2))) + (x13^2 / ((x14 / x15)^2 * (x16 / x17)^2))

y = 1 / (((x1 + ((x2 / (x3 / x4)) * (x5 / (x6 / x7)))) / (x8 / ((x9 / x10) * (x11 / x12)))) + (x13 / ((x14 / x15) * (x16 / x17))))

y = exp(((x1 + ((x2 / (x3 / x4)) * (x5 / (x6 / x7)))) / (x8 / ((x9 / x10) * (x11 / x12)))) + (x13 / ((x14 / x15) * (x16 / x17))))

y = x1 + (((x2 / (x3 / x4)) * (x5 / (x6 / x7))) / (x8 / ((x9 / x10) * (x11 / x12)))) + (x13 / ((x14 / x15) * (x16 / x17)))


y = x1 + x2 + x3 + x4 + x5

y = x1 * x2 * x3 * x4 * x5

y = x1^2 + x2^2 + x3^2 + x4^2 + x5^2

y = x1^3 + x2^3 + x3^3 + x4^3 + x5^3

y = sqrt(x1) + sqrt(x2) + sqrt(x3) + sqrt(x4) + sqrt(x5)

y = 1/x1 + 1/x2 + 1/x3 + 1/x4 + 1/x5

y = e^x1 + e^x2 + e^x3 + e^x4 + e^x5

y = log(x1) + log(x2) + log(x3) + log(x4) + log(x5)

y = sin(x1) + sin(x2) + sin(x3) + sin(x4) + sin(x5)

y = cos(x1) + cos(x2) + cos(x3) + cos(x4) + cos(x5)

y = tan(x1) + tan(x2) + tan(x3) + tan(x4) + tan(x5)

y = x1 + x2 + x3 + x4 + x5 + x1*x2 + x1*x3 + x1*x4 + x1*x5 + x2*x3 + x2*x4 + x2*x5 + x3*x4 + x3*x5 + x4*x5

y = x1 + x2 + x3 + x4 + x5 + x1*x2*x3 + x1*x2*x4 + x1*x2*x5 + x1*x3*x4 + x1*x3*x5 + x1*x4*x5 + x2*x3*x4 + x2*x3*x5 + x2*x4*x5 + x3*x4*x5

y = x1*x2 + x1*x3 + x1*x4 + x1*x5 + x2*x3 + x2*x4 + x2*x5 + x3*x4 + x3*x5 + x4*x5

y = x1*x2*x3 + x1*x2*x4 + x1*x2*x5 + x1*x3*x4 + x1*x3*x5 + x1*x4*x5 + x2*x3*x4 + x2*x3*x5 + x2*x4*x5 + x3*x4*x5

y = x1^2 + x2^2 + x3^2 + x4^2 + x5^2 + x1*x2 + x1*x3 + x1*x4 + x1*x5 + x2*x3 + x2*x4 + x2*x5 + x3*x4 + x3*x5 + x4*x5

y = x1^2 + x2^2 + x3^2 + x4^2 + x5^2 + x1*x2*x3 + x1*x2*x4 + x1*x2*x5 + x1*x3*x4 + x1*x3*x5 + x1*x4*x5 + x2*x3*x4 + x2*x3*x5 + x2*x4*x5 + x3*x4*x5

y = x1*x2 + x1*x3 + x1*x4 + x1*x5 + x2*x3 + x2*x4 + x2*x5 + x3*x4 + x3*x5 + x4*x5 + x1^2 + x2^2 + x3^2 + x4^2 + x5^2

y = x1*x2*x3 + x1*x2*x4 + x1*x2*x5 + x1*x3*x4 + x1*x3*x5 + x1*x4*x5 + x2*x3*x4 + x2*x3*x5 + x2*x4*x5 + x3*x4*x5 + x1^2 + x2^2 + x3^2 + x4^2 + x5^2

y = x1^2*x2 + x1^2*x3 + x1^2*x4 + x1^2*x5 + x2^2*x3 + x2^2*x4 + x2^2*x5 + x3^2*x4 + x3^2*x5 + x4^2*x5 + x1*x2*x3 + x1*x2*x4 + x1*x2*x5 + x1*x3*x4 + x1*x3*x5 + x1*x4*x5 + x2*x3*x4 + x2*x3*x5 + x2*x4*x5 + x3*x4*x5 + x4*x5

y = x1^2*x2*x3 + x1^2*x2*x4 + x1^2*x2*x5 + x1^2*x3*x4 + x1^2*x3*x5 + x1^2*x4*x5 + x2^2*x3*x4 + x2^2*x3*x5 + x2^2*x4*x5 + x3^2*x4*x5 + x1*x2*x3*x4 + x1*x2*x3*x5 + x1*x2*x4*x5 + x1*x3*x4*x5 + x2*x3*x4*x5

y = x1^3 + x2^3 + x3^3 + x4^3 + x5^3 + x1*x2 + x1*x3 + x1*x4 + x1*x5 + x2*x3 + x2*x4 + x2*x5 + x3*x4 + x3*x5 + x4*x5

y = x1^3 + x2^3 + x3^3 + x4^3 + x5^3 + x1*x2*x3 + x1*x2*x4 + x1*x2*x5 + x1*x3*x4 + x1*x3*x5 + x1*x4*x5 + x2*x3*x4 + x2*x3*x5 + x2*x4*x5 + x3*x4*x5

y = x1*x2 + x1*x3 + x1*x4 + x1*x5 + x2*x3 + x2*x4 + x2*x5 + x3*x4 + x3*x5 + x4*x5 + x1^3 + x2^3 + x3^3 + x4^3 + x5^3

y = x1*x2*x3 + x1*x2*x4 + x1*x2*x5 + x1*x3*x4 + x1*x3*x5 + x1*x4*x5 + x2*x3*x4 + x2*x3*x5 + x2*x4*x5 + x3*x4*x5 + x1^3 + x2^3 + x3^3 + x4^3 + x5^3

y = x1^2*x2 + x1^2*x3 + x1^2*x4 + x1^2*x5 + x2^2*x3 + x2^2*x4 + x2^2*x5 + x3^2*x4 + x3^2*x5 + x4^2*x5 + x1*x2*x3 + x1*x2*x4 + x1*x2*x5 + x1*x3*x4 + x1*x3*x5 + x1*x4*x5 + x2*x3*x4 + x2*x3*x5 + x2*x4*x5 + x3*x4*x5 + x4*x5 + x1^3 + x2^3 + x3^3 + x4^3 + x5^3


y = 1/(x1*x2) + 1/(x3*x4) + 1/(x5)

y = e^(-x1) + e^(-x2) + e^(-x3) + e^(-x4) + e^(-x5)

y = sqrt(x1) + sqrt(x2) + sqrt(x3) + sqrt(x4) + sqrt(x5)

y = log(x1) + log(x2) + log(x3) + log(x4) + log(x5)

y = 1/x1 + 1/x2 + 1/x3 + 1/x4 + 1/x5

y = sin(x1) + sin(x2) + sin(x3) + sin(x4) + sin(x5)

y = cos(x1) + cos(x2) + cos(x3) + cos(x4) + cos(x5)

y = tan(x1) + tan(x2) + tan(x3) + tan(x4) + tan(x5)

y = x1 + 2*x2 + 3*x3 + 4*x4 + 5*x5

y = -x1 + -2*x2 + -3*x3 + -4*x4 + -5*x5

y = x1/x2 + x3/x4 + x5

y = x1*x2 + x3*x4 + x5

y = x1^2*x2 + x3^2*x4 + x5^2

y = x1^3*x2 + x3^3*x4 + x5^3

y = 1/x1^2 + 1/x2^2 + 1/x3^2 + 1/x4^2 + 1/x5^2

y = e^(-2*x1) + e^(-2*x2) + e^(-2*x3) + e^(-2*x4) + e^(-2*x5)

y = sqrt(x1)*sqrt(x2) + sqrt(x3)*sqrt(x4) + sqrt(x5)

y = log(x1)*log(x2) + log(x3)*log(x4) + log(x5)

y = 1/(x1^2) + 1/(x2^2) + 1/(x3^2) + 1/(x4^2) + 1/(x5^2)

y = sin(x1)*sin(x2) + sin(x3)*sin(x4) + sin(x5)

y = cos(x1)*cos(x2) + cos(x3)*cos(x4) + cos(x5)

y = tan(x1)*tan(x2) + tan(x3)*tan(x4) + tan(x5)
```

