---
title: "Chat GPT Models"
author: "Daniel K Baissa"
date: "2023-02-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Create Random Varaibles

```{r}
# Load libraries
library(tidyverse)
library(regclass)

# Generate sample data
set.seed(123)
n = 2000
beta1 = rnorm(n)
beta2 = rnorm(n)
beta3 = rnorm(n)
beta4 = rnorm(n)
beta5 = rnorm(n)

X <- cbind(beta1, beta2, beta3, beta4, beta5)
```


## Randomly generated Equations

```{r}


# Calculate z1
z1 = 2 + sin(beta1 * pi) * log(beta2 + exp(beta3)) + cos(beta4) ^ (exp(beta5)) + rnorm(n)
pr1 = 1 / (1 + exp(-z1))

# Calculate z2
z2 = 3 + tan(beta1 + pi) * log(beta2 ^ (exp(beta3))) * sin(beta4 + beta5)+ rnorm(n)
pr2 = 1 / (1 + exp(-z2))

# Calculate z3
z3 = 4 + cos(beta1 * pi) ^ (log(beta2) * exp(beta3)) * log(beta4 + exp(beta5)) ^ (sin(beta1 + beta5) / pi)+ rnorm(n)
pr3 = 1 / (1 + exp(-z3))

# Calculate z4
z4 = 5 + cos(beta1) * log(beta2 + exp(beta3)) ^ (sin(beta4) * exp(beta5))+ rnorm(n)
pr4 = 1 / (1 + exp(-z4))

# Calculate z5
z5 = 6 + sin(beta1 + pi) * log(beta2 ^ (exp(beta3))) + cos(beta4) * exp(beta5)+ rnorm(n)
pr5 = 1 / (1 + exp(-z5))

# Calculate z6
z6 = 7 + cos(beta1) * log(beta2 + exp(beta3)) + sin(beta4) ^ (exp(beta5))+ rnorm(n)
pr6 = 1 / (1 + exp(-z6))

# Calculate z7
z7 = 8 + sin(beta1) * log(beta2 + exp(beta3)) + cos(beta4) * exp(beta5)+ rnorm(n)
pr7 = 1 / (1 + exp(-z7))

# Calculate z8
z8 = 9 + tan(beta1) * log(beta2 ^ (exp(beta3))) * cos(beta4 + beta5)+ rnorm(n)
pr8 = 1 / (1 + exp(-z8))

z9 = 10 + cos(beta1 * pi) ^ (log(beta2) * exp(beta3)) * sin(beta4 + beta5) ^ (log(beta1) + exp(beta5))+ rnorm(n)
pr9 = 1 / (1 + exp(-z9))

# Calculate z10
z10 = 11 + sin(beta1) * log(beta2 + exp(beta3)) + cos(beta4) ^ (exp(beta5))+ rnorm(n)
pr10 = 1 / (1 + exp(-z10))

# Calculate z11
z11 = 12 + log(beta1 + exp(beta2)) * sin(beta3) + cos(beta4) ^ (log(beta5))+ rnorm(n)
pr11 = 1 / (1 + exp(-z11))

# Calculate z12
z12 = 13 + cos(beta1) ^ (exp(beta2)) * log(beta3 + exp(beta4)) + sin(beta5)+ rnorm(n)
pr12 = 1 / (1 + exp(-z12))

# Calculate z13
z13 = 14 + sin(beta1) * exp(beta2) * log(beta3) + cos(beta4) ^ (log(beta5))+ rnorm(n)
pr13 = 1 / (1 + exp(-z13))

# Calculate z14
z14 = 15 + log(beta1) * exp(beta2) + sin(beta3) * cos(beta4) ^ (log(beta5))+ rnorm(n)
pr14 = 1 / (1 + exp(-z14))

# Calculate z15
z15 = 16 + sin(beta1) * log(beta2) * cos(beta3) ^ (exp(beta4)) + log(beta5)+ rnorm(n)
pr15 = 1 / (1 + exp(-z15))

# Calculate z16
z16 = 17 + cos(beta1) * log(beta2 + exp(beta3)) * sin(beta4) + exp(beta5)+ rnorm(n)
pr16 = 1 / (1 + exp(-z16))

# Calculate z17
z17 = 18 + cos(beta1) ^ (exp(beta2)) * sin(beta3) * log(beta4 + exp(beta5))+ rnorm(n)
pr17 = 1 / (1 + exp(-z17))

# Calculate z18
z18 = 19 + log(beta1) * sin(beta2) * cos(beta3) + exp(beta4) ^ (log(beta5))+ rnorm(n)
pr18 = 1 / (1 + exp(-z18))

# Calculate z19
z19 = 20 + cos(beta1) * exp(beta2) + log(beta3) * sin(beta4) ^ (log(beta5))+ rnorm(n)
pr19 = 1 / (1 + exp(-z19))

# Calculate z20
z20 = 21 + sin(beta1) * exp(beta2) * cos(beta3) + log(beta4) ^ (exp(beta5))+ rnorm(n)
pr20 = 1 / (1 + exp(-z20))

# Calculate z21
z21 = 22 + cos(beta1) ^ (log(beta2)) * log(beta3 + exp(beta4)) + sin(beta5)+ rnorm(n)
pr21 = 1 / (1 + exp(-z21))

# Calculate z22
z22 = 23 + log(beta1) * cos(beta2) * sin(beta3) ^ (exp(beta4)) + log(beta5)+ rnorm(n)
pr22 = 1 / (1 + exp(-z22))

# Calculate z23
z23 = 24 + log(beta1) * sin(beta2) * cos(beta3) ^ (log(beta4)) + exp(beta5)+ rnorm(n)
pr23 = 1 / (1 + exp(-z23))

# Calculate z24
z24 = 25 + sin(beta1) * log(beta2 + exp(beta3)) * cos(beta4) + exp(beta5)+ rnorm(n)
pr24 = 1 / (1 + exp(-z24))

# Calculate z25
z25 = 26 + cos(beta1) * sin(beta2) * log(beta3) + exp(beta4) ^ (log(beta5))+ rnorm(n)
pr25 = 1 / (1 + exp(-z25))

# Calculate z26
z26 = 27 + log(beta1 + exp(beta2)) * sin(beta3) * cos(beta4) ^ (log(beta5))+ rnorm(n)
pr26 = 1 / (1 + exp(-z26))

# Calculate z27
z27 = 28 + cos(beta1) * exp(beta2) * sin(beta3) + log(beta4) ^ (exp(beta5))+ rnorm(n)
pr27 = 1 / (1 + exp(-z27))

# Calculate z28
z28 = 29 + sin(beta1) * log(beta2) * cos(beta3) ^ (exp(beta4)) + log(beta5)+ rnorm(n)
pr28 = 1 / (1 + exp(-z28))

# Calculate z29
z29 = 30 + log(beta1) * cos(beta2) * sin(beta3) ^ (log(beta4)) + exp(beta5)+ rnorm(n)
pr29 = 1 / (1 + exp(-z29))

# Calculate z30
z30 = 31 + sin(beta1) * cos(beta2) * log(beta3) + exp(beta4) ^ (log(beta5))+ rnorm(n)
pr30 = 1 / (1 + exp(-z30))

# Calculate z31
z31 = 32 + log(beta1 + sin(beta2)) * cos(beta3) * exp(beta4) ^ (log(beta5))+ rnorm(n)
pr31 = 1 / (1 + exp(-z31))

# Calculate z32
z32 = 33 + cos(beta1) * log(beta2) * sin(beta3) + exp(beta4) ^ (log(beta5))+ rnorm(n)
pr32 = 1 / (1 + exp(-z32))

# Calculate z33
z33 = 34 + sin(beta1) * cos(beta2) * exp(beta3) + log(beta4) ^ (exp(beta5))+ rnorm(n)
pr33 = 1 / (1 + exp(-z33))

# Calculate z34
z34 = 35 + log(beta1) * sin(beta2) * cos(beta3) ^ (exp(beta4)) + log(beta5)+ rnorm(n)
pr34 = 1 / (1 + exp(-z34))

# Calculate z35
z35 = 36 + cos(beta1) * log(beta2) * sin(beta3) + exp(beta4) ^ (log(beta5))+ rnorm(n)
pr35 = 1 / (1 + exp(-z35))

# Calculate z36
z36 = 37 + sin(beta1) * cos(beta2) * log(beta3) + exp(beta4) ^ (log(beta5))+ rnorm(n)
pr36 = 1 / (1 + exp(-z36))

# Calculate z37
z37 = 38 + log(beta1 + sin(beta2)) * cos(beta3) * exp(beta4) ^ (log(beta5))+ rnorm(n)
pr37 = 1 / (1 + exp(-z37))

# Calculate z38
z38 = 39 + cos(beta1) * log(beta2) * sin(beta3) + exp(beta4) ^ (log(beta5))+ rnorm(n)
pr38 = 1 / (1 + exp(-z38))

# Calculate z39
z39 = 40 + sin(beta1) * cos(beta2) * exp(beta3) + log(beta4) ^ (exp(beta5))+ rnorm(n)
pr39 = 1 / (1 + exp(-z39))

# Calculate z40
z40 = 41 + log(beta1) * sin(beta2) * cos(beta3) ^ (exp(beta4)) + log(beta5)+ rnorm(n)
pr40 = 1 / (1 + exp(-z40))

z41 = 42 + cos(beta1 + beta2) * sin(beta3) * log(beta4) + exp(beta5)+ rnorm(n)
pr41 = 1 / (1 + exp(-z41))

z42 = 43 + log(beta1) * cos(beta2) * sin(beta3) + exp(beta4 + beta5)+ rnorm(n)
pr42 = 1 / (1 + exp(-z42))

z43 = 44 + sin(beta1) * log(beta2) * cos(beta3) + exp(beta4 * beta5)+ rnorm(n)
pr43 = 1 / (1 + exp(-z43))

z44 = 45 + cos(beta1) * sin(beta2) * log(beta3) + exp(beta4 / beta5)+ rnorm(n)
pr44 = 1 / (1 + exp(-z44))

z45 = 46 + log(beta1 + beta2) * cos(beta3) * sin(beta4) + exp(beta5)+ rnorm(n)
pr45 = 1 / (1 + exp(-z45))

z46 = 47 + sin(beta1) * log(beta2) * cos(beta3) + exp(beta4 - beta5)+ rnorm(n)
pr46 = 1 / (1 + exp(-z46))

z47 = 48 + cos(beta1) * sin(beta2) * log(beta3) + exp(beta4 + beta5)+ rnorm(n)
pr47 = 1 / (1 + exp(-z47))

z48 = 49 + log(beta1) * cos(beta2) * sin(beta3) + exp(beta4 - beta5)+ rnorm(n)
pr48 = 1 / (1 + exp(-z48))

z49 = 50 + sin(beta1) * log(beta2) * cos(beta3) + exp(beta4 * beta5)+ rnorm(n)
pr49 = 1 / (1 + exp(-z49))

z50 = 51 + cos(beta1) * sin(beta2) * log(beta3) + exp(beta4 / beta5) + rnorm(n)
pr50 = 1 / (1 + exp(-z50))

```

```{r}
y1 = rbinom(n/2, 1, pr1[1:(n/2)])
y1.1 = rbinom(n/2, 1, pr1[((n/2)+1):n])

y2 = rbinom(n/2, 1, pr2[1:(n/2)])
y2.1 = rbinom(n/2, 1, pr2[(n/2):n])

y3 = rbinom(n/2, 1, pr3[1:(n/2)])
y3.1 = rbinom(n/2, 1, pr3[(n/2):n])

y4 = rbinom(n/2, 1, pr4[1:(n/2)])
y4.1 = rbinom(n/2, 1, pr4[(n/2):n])

y5 = rbinom(n/2, 1, pr5[1:(n/2)])
y5.1 = rbinom(n/2, 1, pr5[(n/2):n])

y6 = rbinom(n/2, 1, pr6[1:(n/2)])
y6.1 = rbinom(n/2, 1, pr6[(n/2):n])

y7 = rbinom(n/2, 1, pr7[1:(n/2)])
y7.1 = rbinom(n/2, 1, pr7[(n/2):n])

y8 = rbinom(n/2, 1, pr8[1:(n/2)])
y8.1 = rbinom(n/2, 1, pr8[(n/2):n])

y9 = rbinom(n/2, 1, pr9[1:(n/2)])
y9.1 = rbinom(n/2, 1, pr9[(n/2):n])

y10 = rbinom(n/2, 1, pr10[1:(n/2)])
y10.1 = rbinom(n/2, 1, pr10[(n/2):n])

y11 = rbinom(n/2, 1, pr11[1:(n/2)])
y11.1 = rbinom(n/2, 1, pr11[(n/2):n])

y12 = rbinom(n/2, 1, pr12[1:(n/2)])
y12.1 = rbinom(n/2, 1, pr12[(n/2):n])

y13 = rbinom(n/2, 1, pr13[1:(n/2)])
y13.1 = rbinom(n/2, 1, pr13[(n/2):n])

y14 = rbinom(n/2, 1, pr14[1:(n/2)])
y14.1 = rbinom(n/2, 1, pr14[(n/2):n])

y15 = rbinom(n/2, 1, pr15[1:(n/2)])
y15.1 = rbinom(n/2, 1, pr15[(n/2):n])

y16 = rbinom(n/2, 1, pr16[1:(n/2)])
y16.1 = rbinom(n/2, 1, pr16[(n/2):n])

y17 = rbinom(n/2, 1, pr17[1:(n/2)])
y17.1 = rbinom(n/2, 1, pr17[(n/2):n])

y18 = rbinom(n/2, 1, pr18[1:(n/2)])
y18.1 = rbinom(n/2, 1, pr18[(n/2):n])

y19 = rbinom(n/2, 1, pr19[1:(n/2)])
y19.1 = rbinom(n/2, 1, pr19[(n/2):n])

y20 = rbinom(n/2, 1, pr20[1:(n/2)])
y20.1 = rbinom(n/2, 1, pr20[(n/2):n])

y21 = rbinom(n/2, 1, pr21[1:(n/2)])
y21.1 = rbinom(n/2, 1, pr21[(n/2):n])

y22 = rbinom(n/2, 1, pr22[1:(n/2)])
y22.1 = rbinom(n/2, 1, pr22[(n/2):n])

y23 = rbinom(n/2, 1, pr23[1:(n/2)])
y23.1 = rbinom(n/2, 1, pr23[(n/2):n])

y24 = rbinom(n/2, 1, pr24[1:(n/2)])
y24.1 = rbinom(n/2, 1, pr24[(n/2):n])

y25 = rbinom(n/2, 1, pr25[1:(n/2)])
y25.1 = rbinom(n/2, 1, pr25[(n/2):n])

y26 = rbinom(n/2, 1, pr26[1:(n/2)])
y26.1 = rbinom(n/2, 1, pr26[(n/2):n])

y27 = rbinom(n/2, 1, pr27[1:(n/2)])
y27.1 = rbinom(n/2, 1, pr27[(n/2):n])

y28 = rbinom(n/2, 1, pr28[1:(n/2)])
y28.1 = rbinom(n/2, 1, pr28[(n/2):n])

y29 = rbinom(n/2, 1, pr29[1:(n/2)])
y29.1 = rbinom(n/2, 1, pr29[(n/2):n])

y30 = rbinom(n/2, 1, pr30[1:(n/2)])
y30.1 = rbinom(n/2, 1, pr30[(n/2):n])

y31 = rbinom(n/2, 1, pr31[1:(n/2)])
y31.1 = rbinom(n/2, 1, pr31[(n/2):n])

y32 = rbinom(n/2, 1, pr32[1:(n/2)])
y32.1 = rbinom(n/2, 1, pr32[(n/2):n])

y33 = rbinom(n/2, 1, pr33[1:(n/2)])
y33.1 = rbinom(n/2, 1, pr33[(n/2):n])

y34 = rbinom(n/2, 1, pr34[1:(n/2)])
y34.1 = rbinom(n/2, 1, pr34[(n/2):n])

y35 = rbinom(n/2, 1, pr35[1:(n/2)])
y35.1 = rbinom(n/2, 1, pr35[(n/2):n])

y36 = rbinom(n/2, 1, pr36[1:(n/2)])
y36.1 = rbinom(n/2, 1, pr36[(n/2):n])

y37 = rbinom(n/2, 1, pr37[1:(n/2)])
y37.1 = rbinom(n/2, 1, pr37[(n/2):n])

y38 = rbinom(n/2, 1, pr38[1:(n/2)])
y38.1 = rbinom(n/2, 1, pr38[(n/2):n])

y39 = rbinom(n/2, 1, pr39[1:(n/2)])
y39.1 = rbinom(n/2, 1, pr39[(n/2):n])

y40 = rbinom(n/2, 1, pr40[1:(n/2)])
y40.1 = rbinom(n/2, 1, pr40[(n/2):n])

y41 = rbinom(n/2, 1, pr41[1:(n/2)])
y41.1 = rbinom(n/2, 1, pr41[(n/2):n])

y42 = rbinom(n/2, 1, pr42[1:(n/2)])
y42.1 = rbinom(n/2, 1, pr42[(n/2):n])

y43 = rbinom(n/2, 1, pr43[1:(n/2)])
y43.1 = rbinom(n/2, 1, pr43[(n/2):n])

y44 = rbinom(n/2, 1, pr44[1:(n/2)])
y44.1 = rbinom(n/2, 1, pr44[(n/2):n])

y45 = rbinom(n/2, 1, pr45[1:(n/2)])
y45.1 = rbinom(n/2, 1, pr45[(n/2):n])

y46 = rbinom(n/2, 1, pr46[1:(n/2)])
y46.1 = rbinom(n/2, 1, pr46[(n/2):n])

y47 = rbinom(n/2, 1, pr47[1:(n/2)])
y47.1 = rbinom(n/2, 1, pr47[(n/2):n])

y48 = rbinom(n/2, 1, pr48[1:(n/2)])
y48.1 = rbinom(n/2, 1, pr48[(n/2):n])

y49 = rbinom(n/2, 1, pr49[1:(n/2)])
y49.1 = rbinom(n/2, 1, pr49[(n/2):n])

y50 = rbinom(n/2, 1, pr50[1:(n/2)])
y50.1 = rbinom(n/2, 1, pr50[(n/2):n])




```



Now let's put this into a dataset

```{r}
df.y = data.frame(y1,y2,y3,y4,y5,y6,y7,y8,y9,y10,y11,y12,y13,y14,y15,y16,y17,y18,y19,y20,y21,y22,y23,y24,y25,y26,y27,y28,y29,y30,y31,y32,y33,y34,y35,y36,y37,y38,y39,y40,y41,y42,y43,y44,y45,y46,y47,y48,y49,y50)

df.y1 = data.frame(y1.1, y2.1, y3.1, y4.1, y5.1, y6.1, y7.1, y8.1, y9.1, y10.1, y11.1, y12.1, y13.1, y14.1, y15.1, y16.1, y17.1, y18.1, y19.1, y20.1, y21.1, y22.1, y23.1, y24.1, y25.1, y26.1, y27.1, y28.1, y29.1, y30.1, y31.1, y32.1, y33.1, y34.1, y35.1, y36.1, y37.1, y38.1, y39.1, y40.1, y41.1, y42.1, y43.1, y44.1, y45.1, y46.1, y47.1, y48.1, y49.1, y50.1)

```

```{r}
summary(y20)
summary(y20.1)

```
Now I will set all NAs to zero since they are underrepresented in the data

```{r}
df.y[is.na(df.y)] <- 0
df.y1[is.na(df.y1)] <- 0

```


```{r}
summary(df.y$y20)
```



```{r}

df <- as.data.frame(cbind(y = df.y[,1], X[1:(n/2)]))
df_out_of_sample <- df.y1[,1] 

m2.glm <- glm(y~., data = df,family="binomial")

cm <- confusion_matrix(m2.glm)

# 1-(cm[1, 1]/cm[1, 3])
# 1-(cm[2, 2]/cm[2, 3])

cm
```

```{r}
# Training set data frame
df <- as.data.frame(cbind(y = df.y[,1], X[1:(n/2)]))
m2.glm <- glm(y~., data = df, family="binomial")

# Testing set data frame
df_test <- as.data.frame(cbind(y = df.y1[,1], X[(n/2):n]))

# Generate predictions for the testing set
predictions <- predict(m2.glm, newdata = df_test, type = "response")

# Convert predictions into binary (0 or 1) using a threshold (e.g., 0.5)
threshold <- 0.5
binary_predictions <- ifelse(predictions > threshold, 1, 0)

# Compare the predicted values to the true values
true_values <- df_test$y
accuracy <- mean(binary_predictions == true_values)
cat("Out-of-sample accuracy:", accuracy, "\n")

```


```{r}
require(rJava)
options(java.parameters = "-Xmx50g")     # or 8g, or larger than this, ...
require(bartMachine)
set_bart_machine_num_cores(8)
```

```{r}
df$y <- as.factor(df$y)
# df <- data.frame(df)
class(df)
# bm2 <- bartMachineCV(Xy = df)
# bm <- bartMachine(y = as.data.frame(df$y), X = as.data.frame(X))

bm <- bartMachine(y = as.factor(df.y[,1]), X = as.data.frame(X[1:(n/2),]))
```

```{r}
bm
```

```{r}

# Train the bartMachine model
bm <- bartMachine(y = as.factor(df.y[,1]), X = as.data.frame(X[1:(n/2),]))

# Testing set data frame
df_test <- as.data.frame(X[((n/2)+1):n,])
true_values <- as.factor(df.y1[,1])

# Generate predictions for the testing set
predictions_prob <- predict(bm, new_data = df_test, type = "prob")
# Since you have probabilities, convert them into binary (0 or 1) using a threshold (e.g., 0.5)
threshold <- 0.5
binary_predictions <- ifelse(predictions_prob < threshold, 1, 0)

# Compare the predicted values to the true values
accuracy <- mean(binary_predictions == true_values)
cat("Out-of-sample accuracy:", accuracy, "\n")

```


```{r}
# BartModelErrors <- as.data.frame(cbind(Actual0 = bm[["confusion_matrix"]][["model errors"]][1],
#                                        Actual1 = bm[["confusion_matrix"]][["model errors"]][2],
#                                        Total = bm[["confusion_matrix"]][["model errors"]][3]))

BartModelErrors <- as.data.frame(cbind(Actual0 = NA,
                                       Actual1 = NA,
                                       Total = NA))

```

```{r}
# rbind(BartModelErrors, BartModelErrors)
```

## Generating A bunch of Bart Models

```{r}


for (i in 1:length(colnames(df.y))) {
  
  y <- as.factor(df.y[,i])

  
  bm <- bartMachine(y = y, X = as.data.frame(X))
    cf <- as.data.frame(cbind(Actual0 = bm[["confusion_matrix"]][["model errors"]][1],
                                       Actual1 = bm[["confusion_matrix"]][["model errors"]][2],
                                       Total = bm[["confusion_matrix"]][["model errors"]][3]))
BartModelErrors <- rbind(BartModelErrors, cf)
}

```

```{r}
BartModelErrors <- na.omit(BartModelErrors)

mean(BartModelErrors$Actual0)
mean(BartModelErrors$Actual1)
mean(BartModelErrors$Total)
```
## Logit Model Use errors

```{r}
df <- as.data.frame(cbind(y = df.y[,12], X))

m2.glm <- glm(y~., data = df,family="binomial")

confusion_matrix(m2.glm)
cm[1, 2]/cm[1, 3]
cm[2, 1]/cm[2, 3]
((cm[2, 1])+(cm[2, 1]))/cm[3,3]
```

```{r}
LogitModelErrors <- as.data.frame(cbind(Actual0 = NA,
                                       Actual1 = NA,
                                       Total = NA))
```

```{r}

for (i in 1:length(colnames(df.y))) {
  
  df <- as.data.frame(cbind(y = df.y[,i], X))
  m.glm <- glm(y~., data = df,family="binomial")
  
 cm <- confusion_matrix(m.glm)
 cm[1, 2]/cm[1, 3]
 cm[2, 1]/cm[2, 3]
((cm[2, 1])+(cm[2, 1]))/cm[3,3]
 
 
 cf <- as.data.frame(cbind(Actual0 = cm[1, 2]/cm[1, 3],
                                       Actual1 = cm[2, 1]/cm[2, 3],
                                       Total = ((cm[2, 1])+(cm[2, 1]))/cm[3,3]))
 
 
LogitModelErrors <- rbind(LogitModelErrors, cf)
}
```

```{r}
LogitModelErrors <- na.omit(LogitModelErrors)

mean(LogitModelErrors$Actual0)
mean(LogitModelErrors$Actual1)
mean(LogitModelErrors$Total)
```

```{r}
mean(LogitModelErrors$Total)
mean(BartModelErrors$Total)
```

