---
title: "Test"
author: "Daniel K Baissa"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(regclass)

require(rJava)
options(java.parameters = "-Xmx50g")     # or 8g, or larger than this, ...
require(bartMachine)
# set_bart_machine_num_cores(8)
set_bart_machine_num_cores(30)

```



```{r warning=FALSE}

# combine the tibbles into a list
X.l <- list(X = NA)
y.l <- list(y = NA)

# convert the list of tibbles into a tibble of tibbles
X.tb <- as_tibble(X.l)
y.tb <- as_tibble(y.l)


for (i in 1:1000) {

    source("Dataset_generator.R", echo = F)
  
  y = data.frame(y1,y2,y3,y4,y5,y6,y7,y8,y9,y10,y11,y12,y13,y14,y15,y16,y17,y18,y19,y20,y21,y22,y23,y24,y25,y26,y27,y28,y29,y30,y31,y32,y33,y34,y35,y36,y37,y38,y39,y40,y41,y42,y43,y44,y45,y46,y47,y48,y49,y50)

  y[is.na(y)] <- 0

  
# Setting up the y tibble
  y.tb <- cbind(y.tb, as_tibble(list(y = as.data.frame(y))))
  colnames(y.tb)[length(colnames(y.tb))] <- paste0("y_", i)
  
# Setting up the X tibble
  X.tb <- cbind(X.tb, as_tibble(list(X = as.data.frame(X))))
  colnames(X.tb)[length(colnames(X.tb))] <- paste0("X_", i)


}
y.tb[1] <- NULL
X.tb[1] <- NULL
rm(list = setdiff(ls(), c("X.tb", "y.tb")))
```


## Filtering datasets



```{r}
df.l <- list(y = NA)
df.tb <- as_tibble(df.l)

for (j in 1:length(colnames(X.tb))) {
# for (j in 1:1) {
  
  df.y <- y.tb[[j]]
  
  # Select numeric columns
  data.numcols <- df.y[, sapply(df.y, is.numeric)]

  # Using apply
  all.means <- apply(data.numcols, 2, mean)

  # imbalanced <- all.means[which(all.means > .7)]
imbalanced <- all.means[which(all.means < .3)]

  ys <- as.vector(names(imbalanced))

  df.y <- df.y |> 
    select(all_of(ys))
  try(
    

  for (i in 1:length(colnames(df.y))) {
      
    df1 <- X.tb[[j]]
    df1 <- cbind(df1, y = df.y[,i])
    df.tb <- cbind(df.tb, as_tibble(list(df = df1)))
    
    colnames(df.tb)[length(colnames(df.tb))] <- paste0("X_",j-1,"_", i)

    
    }
)
}

df.tb[1] <- NULL

df.tb <- sample(df.tb, 10000)

```




```{r}


df <- df.tb[[1]]
 


m2.glm <- glm(y~., data = df,family="binomial")

cm <- confusion_matrix(m2.glm)
cm
1-(cm[1, 1]/cm[1, 3])
1-(cm[2, 2]/cm[2, 3])
((cm[2, 1])+(cm[2, 1]))/cm[3,3]
```

### Logit Testing

```{r}

LogitModelErrors <- c()

for (i in 1:length(colnames(df.tb))) {
  
  df <- df.tb[[i]]
  m.glm <- glm(y~., data = df,family="binomial")
  
 cm <- confusion_matrix(m.glm)
 cm[1, 2]/cm[1, 3]
 cm[2, 1]/cm[2, 3]
((cm[2, 1])+(cm[2, 1]))/cm[3,3]
 
 
 cf <- as.data.frame(cbind(Actual0 = cm[1, 2]/cm[1, 3],
                                       Actual1 = cm[2, 1]/cm[2, 3],
                                       Total = ((cm[2, 1])+(cm[2, 1]))/cm[3,3]))
 
 
LogitModelErrors <- rbind(LogitModelErrors, cf)
}
```

```{r}
LogitModelErrors <- na.omit(LogitModelErrors)

mean(LogitModelErrors$Actual0)
mean(LogitModelErrors$Actual1)
mean(LogitModelErrors$Total)


as.data.frame(LogitModelErrors$Actual0) |> 
  ggplot(aes(x = LogitModelErrors$Actual0))+
  geom_histogram()

as.data.frame(LogitModelErrors$Actual1) |> 
  ggplot(aes(x = LogitModelErrors$Actual1))+
  geom_histogram()

as.data.frame(LogitModelErrors$Total) |> 
  ggplot(aes(x = LogitModelErrors$Total))+
  geom_histogram()


```
## BART
```{r include=FALSE}

start_time <- Sys.time()
BartModelErrors <- c()
for (i in 1:length(colnames(df.tb))) {
  
  df.tb[[i]]$y <- as.factor(df.tb[[i]]$y)
  bm <- bartMachine(Xy= df.tb[[i]])
  
      cf <- as.data.frame(cbind(Actual0 = bm[["confusion_matrix"]][["model errors"]][1],
                                       Actual1 = bm[["confusion_matrix"]][["model errors"]][2],
                                       Total = bm[["confusion_matrix"]][["model errors"]][3]))
      
      BartModelErrors <- rbind(BartModelErrors, cf)

}

end_time <- Sys.time()
time_taken <- end_time - start_time


```

```{r}
BartModelErrors <- na.omit(BartModelErrors)

mean(BartModelErrors$Actual0)
mean(BartModelErrors$Actual1)
mean(BartModelErrors$Total)

hist(BartModelErrors$Actual0)

as.data.frame(BartModelErrors$Actual0) |> 
  ggplot(aes(x = BartModelErrors$Actual0))+
  geom_histogram()

as.data.frame(BartModelErrors$Actual1) |> 
  ggplot(aes(x = BartModelErrors$Actual1))+
  geom_histogram()

as.data.frame(BartModelErrors$Total) |> 
  ggplot(aes(x = BartModelErrors$Total))+
  geom_histogram()
```

### Difference in means between errors

```{r}

t.test(BartModelErrors$Actual0, LogitModelErrors$Actual0)
t.test(BartModelErrors$Actual1, LogitModelErrors$Actual1)
t.test(BartModelErrors$Total, LogitModelErrors$Total)

```

### Saving Enviornment:

```{r}
rm(list = setdiff(ls(), c("df.tb", "BartModelErrors", "LogitModelErrors", "time_taken")))

save(BartModelErrors, file = "BartModelErrors.RData")
save(LogitModelErrors, file = "LogitModelErrors.RData")
save(df.tb, file = "df.tb.RData")

# save.image(file='myEnvironment.RData')
# load('myEnvironment.RData')
```

